### ISSUE TITLE
竞技场名字变123

### ISSUE THREAD

**Issue by TFGH164** [likesc/tinyhub#1]
大佬能增加123位置和大小的调节选项吗？以及支持添加自定义法术id来实现按施法距离来变色123，比如输入变形术，超过36码是什么色，36码以内可以施法了是什么颜色。或者单出这一插件可行吗？现在有这些功能的插件一个都没有。。。。好难。

**Comment by R32** [comment]
这个是由网上的宏改的, 提供不了更多的能力了. 可以看下别的插件例如 : [betterblizzframes](https://www.curseforge.com/wow/addons/betterblizzframes) 是否有你想要的功能

**Comment by TFGH164** [comment]
> 这个是由网上的宏改的, 提供不了更多的能力了. 可以看下别的插件例如 : [betterblizzframes](https://www.curseforge.com/wow/addons/betterblizzframes) 是否有你想要的功能

**Comment by TFGH164** [comment]
这个我试了3.43都不行。。作者也不打算支持3.43，，好难。。

**Comment by R32** [comment]
https://www.curseforge.com/wow/addons/betterblizzplates 好像更好, 一些简单的错误很容易修复的
